### ISSUE TITLE
TODO: V2.2.0

### ISSUE THREAD

**Issue by natnqweb** [natnqweb/Simpletimer#5]
- [ ] add macros (possibly also typedefs) for commonly used cases especially callbacks because im sure Simpletimer::callback feels a little bit weird for beginners. Also passing array to register multiple callbacks seems probably hard for user (that's my opinion)

- [ ] redesign callback so it would be a class thats connected with enum (it would be very handy to create multiple callbacks and connect them with one macro

- [ ] change micros() back to millis()
